.TH tdm 1
.SH NAME
tdm \- a tiny display manager
.SH SYNOPSIS
.B
tdm
[\fB--xstart\fR]
.TP
.B
tdmctl
\fICOMMAND\fR [\fIARGS\fR]
.SH DESCRIPTION
.BR tdm (1)
is a console based display manager, presenting the user with a list of
available sessions after login.  Sessions can be defined by creating symlinks
to various programs or scripts, like your favourite window manager / desktop
environment.
.SH COMMANDS
.TP
.BR init
initialize the config directory.
.TP
.BR list
list available X and extra sessions.
.TP
.BR cache
list cached files.
.TP
.BR check " [extra/]" \fISESSION\fR
see what <session> is.
.TP
.BR default " " [\fISESSION\fR]
.br
show/set default X session.
.TP
.BR add " " \fINAME\fR " " \fIPATH\fR " " [\fICATEGORY\fR]
add a session (\fICATEGORY\fR can be either \fIX\fR or \fIextra\fR).
.TP
.BR remove " " \fINAME\fR
remove a session.
.TP
.BR enable " " \fISESSION\fR
enable \fISESSION\fR
.TP
.BR disable " " \fISESSION\fR
disable \fISESSION\fR
.SH RETURN VALUE
If no session was executed, returns 1. Otherwise 0.
.SH FILES AND DIRECTORIES
.TP
.BR ~/.tdm/tdminit
commands executed at login
.TP
.BR ~/.tdm/tdmexit
commands executed before the X server (or extra session) is started
